name: CI PWA FocusTimer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4


    - name: Start Docker Containers
      run: docker compose up -d --build

    - name: Wait for Server
      run: sleep 15

    - name: Verify PWA is Online
      run: |
        echo "Tentando conectar em localhost:8080..."
        curl -v --fail http://localhost:8080
        echo "✅ SUCESSO: O PWA está rodando e acessível!"

    - name: Verify API is Online
      run: |
        echo "Tentando conectar na API..."
        curl -v --fail http://localhost:3000
        echo "✅ SUCESSO: A API está rodando!"