name: CI PWA FocusTimer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Playwright Lib
      run: npm install -D @playwright/test

    - name: Install Browsers
      run: npx playwright install --with-deps chromium

    - name: Start Docker Containers
      run: docker compose up -d --build

    - name: Wait for Server
      run: sleep 15

    - name: Check PWA is Online
      run: |
        curl -v http://localhost:8080 || exit 1
        echo "PWA is running successfully!"